available=Available for use
owned=In use by {0}
baud-rate=Baud rate
stop-bits=Stop bits
parity=Parity
active=You are connected to @'{'bold {0}'}'
inactive=You are not connected to any serial port.
alreadyConnected=You are already successfully connected to {0}.
connectedToOther=You are currently connected to {0}, so must disconnect from that first before connecting to {1}.
inUse={0} is currently in use by {1}.
connected=Successfully connected to @'{'bold {0}'}' @ @'{'bold {1}'}' baud 
notConnected=Not connected to any serial port.
disconnected=Successfully disconnected from @'{'bold {0}'}'
noneActive=Serial port must be specified, as none are currently active.
configured=Successfully reconfigured @'{'bold {0}'}'
noSuchPort=No such serial port: {0}
noPorts=No serial ports found.