confirm=Make sure the receiving device is running a XMODEM sender and \
	is ready to send data, then press RETURN
received=Received {0}
noFileSelected=No file selected.
receive=Receive File using XMODEM