confirm=Make sure the receiving device is running a YMODEM sender and \
	is ready to send data, then press RETURN
received=Received {0}
noFileSelected=No file selected.
noDirectorySelected=No directory selected.
receive=Receive File using YMODEM
receiveDirectory=Receive Directory using YMODEM
batchMustBeDirectory=Batch mode requires a directory path.
singleMustBeFile=Single file mode requires a file path.
