confirm=Make sure the receiving device is running a YMODEM receiver and \
	is ready to receive data, then press RETURN
sent=Sent {0}
noFileSelected=No file selected.
send=Send File using YMODEM
multiple={0} files