confirm=Make sure the receiving device is running a ZMODEM sender and \
	is ready to send data, then press RETURN
received=Received {0}
noFileSelected=No file selected.
noDireectorySelected=No directory selected.
receive=Receive File using ZMODEM
receiveDirectory=Receive Directory using ZMODEM
mustBeDirectory=Batch mode requires a directory path.
