active=You are connected via telnet to @'{'bold {0}'}'
inactive=You are not connected to any telnet host.
alreadyConnected=You are already connected to {0}.
connectedToOther=You are currently connected to {0}, so must disconnect from that first.
connected=Connected to @'{'bold {0}'}'
disconnected=Successfully disconnected from @'{'bold {0}'}'
notConnected=Not connected to any telnet host.
hostname=Hostname (@{bold hostname}[:@{bold port}]):
hostname.right=Return for @'{'bold {0}'}'
noPromptOrDestination=If no destination is provided, --prompt must be provided to be prompted.
