window.heading=Window
window.new-tab.label=New Tab
window.new-window.label=New Windows
window.close.label=Close Tab Or Window
window.rename-tab.label=Rename Tab
window.detach-tab.label=Detach Tab
window.full-screen.label=Full Screen
window.split-horizontal.label=Split Horizontal
window.split-vertical.label=Split Vertical

terminal.heading=Terminal
terminal.select-all.label=Select All
terminal.copy.label=Copy
terminal.paste.label=Paste
terminal.mute.label=Mute
terminal.scroll-up.label=Scroll Up
terminal.scroll-down.label=Scroll Down
terminal.page-up.label=Page Up
terminal.page-down.label=Page Down
terminal.top.label=Scroll To Top
terminal.bottom.label=Scroll To Bottom

app.heading=Application
app.about.label=About
app.actions.label=Actions
app.options.label=Options
app.toggle-pricli.label=Subshell