;
; Window
;

[window]
	name = Window 

[window.new-tab]
	accelerator = CTRL+SHIFT+T
	on = new-button, tty
	
[window.new-window]
	accelerator = CTRL+SHIFT+N
	on = new-button, tty
	
[window.close]
	accelerator = CTRL+SHIFT+W
	on = tab, tty
	
[window.rename-tab]
	command = tab
	arguments = rename
	accelerator = CTRL+SHIFT+R
	on = tab, tty
	
[window.detach-tab]
	command = tab
	arguments = detach
	accelerator = CTRL+SHIFT+D
	on = tab, tty
	
[window.full-screen]
	accelerator = F11
	on = tty
	
;
; Terminal
;
	
[terminal]
	name = Terminal
	
[terminal.select-all]
	accelerator = CTRL+SHIFT+A
	on = context, cli-context, tty, cli
	
[terminal.copy]
	accelerator = CTRL+SHIFT+C
	on = context, cli-context, tty, cli
	
[terminal.paste]
	accelerator = CTRL+SHIFT+V
	on = context, cli-context, tty, cli
	
[terminal.mute]
	accelerator = CTRL+SHIFT+M
	on = new-button, tty
	
[terminal.scroll-up]
	command = scroll
	arguments = "line", "-1"
	accelerator = CTRL+SHIFT+UP
	on = tty, cli
	
[terminal.scroll-down]
	command = scroll
	arguments = "line", "+1"
	accelerator = CTRL+SHIFT+DOWN
	on = tty, cli
	
[terminal.page-up]
	command = scroll
	arguments = "page", "-1"
	accelerator = SHIFT+PAGE UP
	on = tty, cli
	
[terminal.page-down]
	command = scroll
	arguments = "page", "+1"
	accelerator = SHIFT+PAGE DOWN
	on = tty, cli
	
[terminal.top]
	command = scroll
	arguments = "top"
	accelerator = SHIFT+HOME
	on = tty, cli
	
[terminal.bottom]
	command = scroll
	arguments = "bottom"
	accelerator = SHIFT+END
	on = tty, cli
	
;
; Application
;
	
[app]
	name = Application
	
[app.about]
	on = context, tty
	arguments = --dialog
	
[app.actions]
	accelerator = 'CTRL+.'
	on = context, tty
	arguments = --dialog
	
[app.options]
	accelerator = 'CTRL+,'
	on = context, tty
	arguments = --dialog

[app.toggle-pricli]
	command = subshell
	arguments = toggle
	accelerator = ALT+/
	on = context, cli-context, tty, cli
