; Default Configuration

; --------------------------------
; Options for the terminal
; --------------------------------

[terminal]

; Command. The (built in) command to use to provide the initial shell. To use an externl
; command, using 'native <shell> [<args> ..]'. Other options include 'serial' or 'ssh'
; commands.
shell = native 
 
; Terminal type
type = xterm-256color

; Cursor style
cursor-style = BLOCK

; Blinking cursor
cursor-blink = true

; Whether to enable scroll-back at all
scroll-back = true

; Scroll-back buffer size
buffer-size = 32768

; Show a scrollbar when needed. ON always show, OFF never show, 
; AUTO automatically show depending on if there is scrollback content
scroll-bar = AUTO

; Theme. Color theme to use for terminal.
theme = Gray on Black

; Comma separate list of fonts, defining the order they will be queried for glyphs. An 
; empty list means the default font order will be used.
;  
; fonts = "<font name 1>"[, "<font name 2">[, ......]] 
fonts =

; Default font size
font-size = 16

; Resize mode. Can be one of 'SCREEN', 'FONT' or 'NONE'
resize-strategy = SCREEN

; Default screen size.
screen-size = 80x40 

; Background image. File path or URL. When blank, will come from the theme (if any)
background-image = 

; Background type. One of <empty>, NONE, CENTERED, FILL, SCALED, TILED, INHERIT. When
; blank, will come from theme (if any)
background-type = 

; Whether to enable the blink text attribute. 
blinking = true

; Where tabs are positioned. 'TOP', 'BOTTOM', 'LEFT' or 'RIGHT'
tabs = TOP

; How big of a border should there be between the terminal content and the edges
; of the window. Can either be a single value, or 4 comma separated values for
; top, right, bottom, left. If set to 'default', will be take from the theme
padding = default

; Optional features. Each feature may be enabled or disabled by default. 
; Being in one of the two below settings will override this.

enabled-features = 
disabled-features = 

; --------------------------------
; File Transfer Options. 
; 
; --------------------------------
[file-transfer]
notifications = true

; --------------------------------
; Status display is additional screen space that may be written to be the
; host. This feature was supported in the vt320 and above (a single line) 
; and is activated by the DECSASD sequence.
;
; Anything that can be done with the main display can be done with
; the status display;
;
; --------------------------------
[status]

; Whether to show status display. 
enabled = false  

; Height of status display
height = 2

[pricli]

; --------------------------------
; Options for the popup console
; --------------------------------

[pricli]

; Whether to enable scroll-back at all
scroll-back = true

; Scroll-back buffer size
buffer-size = 8000

; Alignment. Where the console popup will appear. Can be 'AUTO', 'TOP' or 'BOTTOM'
align = AUTO

; Height. How high the console popup will be. Can either be a whole number of lines
; >= 1 or a fraction of the window size. 
height = 0.5

; Theme. Name of theme to use for the console popup. When not provided, attached
; terminal theme will be used
; theme = Gray on Black

; --------------------------------
; Other
; --------------------------------

; Environment key / value pairs will be injected into the targets environment, i.e.
; the native console or SSH connection 
[environment]