; Default Configuration

; --------------------------------
; User Interface
; --------------------------------

[ui]
	name = User Interface

[ui.dark-mode]
	name = Dark Mode
	description = Dark user interface (everything but the terminal display itself).
	type = ENUM
	values = dark-modes
	value = AUTO
	value = ALWAYS
	value = NEVER
	default-value = AUTO

[ui.mute]
	name = Mute
	description = Whether to mute all audio (such as terminal bell). Toggled by bell icon.
	type = BOOLEAN
	default-value = false

[ui.password-mode]
	name = Password Mode
	description = Password mode. STORE to store in desktop wallet, SESSION to store in memory, \
					or PROMPT to always prompt.
	type = ENUM
	values = password-modes
	value = STORE
	value = SESSION
	value = PROMPT
	default-value = STORE

[ui.accent-color]
	name = Accent Color
	description = The highlight color used in the user interface.
	type = TEXT
	descriminator = COLOR
	default-value = #0078d7

; --------------------------------
; Options for the terminal
; --------------------------------

[terminal]
	name = Terminal

[terminal.shell]
	name = Shell
	type = TEXT
	description = Shell. The command to use to provide the initial shell. This may either be the  \
				  name of a discovered shell or internal command, or the path of a custom command.\n\
				  \n\
				  If it is a named shell, then any additional arguments will be append to the default arguments for \
				  that shell.\n\
				  \n\
	              If it is a path, then any additional arguments will be passed exactly as is.\n\
				  \n\
	              If it not a path, nor a named shell, then the command must exist on the path, and again \
	              additional arguments will be passed as is.\n\
				  \n\
	              If blank, or 'native', the default local shell will be used and again \
	              additional arguments will be passed as is.\n\
				  \n\
	values = shells
	value = native
	default-value = native
 
[terminal.type]
	nanme = Terminal Type
	type = ENUM
	description = The terminal type specifies the model of the terminal the emulator declares itself as. 
	values = terminal-types
	default-value = xterm-256color
	
[terminal.cursor-style]
	name = Cursor Style
	description = The shape and behaviour of the cursor.
	type = ENUM
	values = cursor-styles
	value = BLOCK
	value = LINE
	value = BAR
	default-value = BLOCK
	
[terminal.cursor-blink]
	name = Cursor Blink
	description = Whether to blink the cursor on and off, to make it easier to see where it is at a glance.
	type = BOOLEAN
	default-value = false
	
[terminal.limit-buffer]
	name = Limit Buffer
	description = Whether to limit the scroll-back buffer size. When false, scroll-back is unlimited. 
	type = BOOLEAN
	default-value = false
	
[terminal.buffer-size]
	name = Buffer Size
	description = Scroll-back buffer size
	type = NUMBER
	default-value = 30000
	value = 0
	
[terminal.buffer-mode]
	name = Buffer Storage Mode
	description = How to store the scroll-back buffer. The "unlimited" buffer is a memory mapped \
			file.   	
	type = ENUM
	values = storage-modes
	value = PLAIN
	value = COMPRESSED
	value = ENCRYPTED
	default-value = ENCRYPTED
	
[terminal.scroll-bar]
	name = Scroll Bar
	description = Show a scrollbar when needed. ON always show, OFF never show,
	type = ENUM
	values = scroll-bar-modes
	value = AUTOMATIC
	value = PERMANENT
	value = HIDDEN
	default-value = AUTOMATIC	
	
[terminal.theme]
	type = ENUM
	name = Theme
	description = Theme. Color theme to use for terminal. This may be any known theme name.
	values = themes
	default-value = Material	
	
[terminal.fonts]
	name = Fonts
	description = Comma separate list of fonts, defining the order they will be queried for glyphs. An \ 
				empty list means the default font order will be used.
	type = LIST
	of = text
	values = fonts
	
[terminal.font-size]
	name = Font Size
	description = Default font size
	default-value = 16
	type = NUMBER
	values = font-sizes
	
[terminal.resize-strategy]
	name = Resize Strategy
	type = ENUM
	values = resize-strategies
	value = SCREEN
	value = FONT
	value = NONE
	default-value = SCREEN
	description = How the terminal behaves when the amount of available space changes, e.g. after a window resize. 
	
[terminal.screen-size]
	name = Screen Size
	type = TEXT
	description = The default screen size, resize strategy dependent.
	value = "132x40"
	value = "80x40"
	value = "80x25"
	value = "80x24"
	default-value = 80x40
	
[terminal.opacity]
	name = Opacity
	type = NUMBER
	min = 0 
	max = 100
	default-value = 95
	description = Opacity of terminal background. The lower the number, the more of the underlying desktop or other windows you will see through the terminal.

[terminal.background-image]
	name = Background Image
	type = TEXT
	discriminator = LOCATION
	browse = true
	default-value = ""
	description = Background image. File path or URL. When blank, will come from the theme (if any).

[terminal.background-type]
	name = Background Type
	description = Background type. When blank, will come from theme (if any).
	type = ENUM
	default-value = NONE
	values = background-types
	value = NONE 
	value = CENTERED
	value = FILL
	value = SCALED
	value = TILED
	value = INHERIT

[terminal.blinking]
	type = BOOLEAN
	name = Blinking
	description = Whether to enable the blink text attribute. 
	default-value  = true

[terminal.tabs] 
	type = ENUM
	name = Tab Position
	description = Where tabs are positioned. 'TOP', 'BOTTOM', 'LEFT' or 'RIGHT'
	value = TOP
	value = BOTTOM
	value = LEFT
	value = RIGHT
	values = tabs
	default-value  = TOP
	
[terminal.padding]
	type = TEXT
	name = Padding
	value = default
	description = How big of a border should there be between the terminal content \
				  and the edges of the window. Can either be a single value, or 4 \
				  comma separated values for top, right, bottom, left. If set to \
				  'default', will be taken from the theme.
	default-value = default
	
[terminal.enabled-features]
	type = LIST
	values = features
	name = Enabled Features
	description = Optional features to enable. Any feature may be disabled by default. \ 
				  Being in this list will override this.
	
[terminal.disabled-features]
	type = LIST
	values = features
	name = Disabled Features
	description = Optional features to disabled. Any feature may be enabled by default. \ 
				  Being in this list will override this.

[terminal.login-shell]
	type = BOOLEAN
	name = Login Shell
	description = Whether to use a "Login Shell" on operating systems that support it. \
				This will have a slightly different environment, as if the user was \
				logging in remotely to a new session. 
	default-value  = false

[terminal.legacy-pty]
	type = BOOLEAN
	name = Legacy Pty
	description = Only applicable to Windows, whether to use "Legacy Pty". The default of \
				  false indicates to use the modern "ConPTY" API.
	default-value = false

[terminal.windows-ansi-color]
	name = Windows ANSI color
	type = BOOLEAN
	description = Whether to enable ANSI color on Windows
	default-value = true

[terminal.preserve-tty]
	name = Preserve Tty
	type = BOOLEAN
	description = Whether to keep the pty open until all output has been received
	default-value = false

[terminal.console]
	name = Console
	type = BOOLEAN
	description = Whether the pty should use "Console Mode", which activates a separate \
				  error stream, and makes some other operating system specific adjustments.
	default-value = false
	
[terminal.password-mode]
	name = Password Mode
	type = ENUM
	values = password-modes
	value = STORE
	value = SESSION
	value = PROMPT
	default-value = STORE
	description = Whether or not passwords should be stored, and if so, how.  

; --------------------------------
; File Transfer Options. 
; 
; --------------------------------
[file-transfer]
	name = File Transfer

[file-transfer.notifications]
	name = Notifications
	type = BOOLEAN
	description = Whether to trigger popup notifications when file transfers complete.
	default-value = true

[file-transfer.downloads]
	name = Download Directory
	type = TEXT
	discriminator = DIRECTORY
	description = Where to save files downloaded from remote hosts (e.g. via iTerm2 file transfer or SFTP).
	default-value = ~/Downloads

; --------------------------------
; Status display is additional screen space that may be written to be the
; host. 
; --------------------------------
[status]
	name = Status
	description = Status display is additional screen space that may be written to be the \
				  host. This feature was supported in the vt320 and above (a single line) \ 
				  and is activated by the DECSASD sequence. \n\
				  \n\
				  Anything that can be done with the main display can be done with \
				  the status display

[status.enabled]
	name = Enabled
	type = BOOLEAN
	description = Whether to show status display.
	default-value = true
	
[status.height]
	name = Height
	type = NUMBER
	description = Height of status display 
	min = 1
	max = 4  
	default-value = 1

; --------------------------------
; Options for the popup console
; --------------------------------

[pricli]
	name = Built-In Shell
	description = Options for the popup console.

[pricli.limit-buffer]
	name = Limit Buffer
	description = Whether to limit the scroll-back buffer size. When false, scroll-back is unlimited. 
	type = BOOLEAN
	default-value = true

[pricli.buffer-size]
	name = Buffer Size
	description = Scroll-back buffer size
	type = NUMBER
	default-value = 30000
	value = 0

[pricli.align]
	type = ENUM
	name = Alignment
	description = Alignment. Where the console popup will appear. Can be 'AUTO', 'TOP' or 'BOTTOM'
	values = alignments
	value = AUTO
	value = TOP
	value = BOTTOM
	default-value = AUTO
	
[pricli.height]
	name = Height 
	type = NUMBER 
	discriminator = FLOAT
	description = Height. How high the console popup will be. Can either be a whole number of lines \
				  >= 1 or a fraction of the window size. 
	default-value  = 0.75

[pricli.theme]
	name = Theme
	type = ENUM
	values = themes
	description = Theme. Name of theme to use for the console popup. When not provided, attached \
				  terminal theme will be used
	default-value = Gray on Black

; --------------------------------
; Debug
; --------------------------------

[debug]
	name = Debug

[debug.verbose-exceptions]
	name = Verbose Exceptions
	type = BOOLEAN
	description = Whether to show full stack traces when errors occur in the console.
	default-value = false

; --------------------------------
; Other
; --------------------------------

[environment]
	name = Environment
	description = Environment key / value pairs will be injected into the targets environment, i.e. \
				  the native console or SSH connection 