
section.terminal=Terminal
section.terminal.description=Configuration for the terminal

section.pricli=Popup Console
section.pricli.description=Configuration for the popup console

section.environment=Environment
section.environment.description=Environment key / value pairs will be injected into the targets environment, i.e. the native console or SSH connection