updates=Updates
automaticUpdates=Automatic Updates
automaticUpdates.toolTip=Whether to automatically update this application.
phase=Update Channel
phase.toolTip=The update channel from which to retrieve updates from.
phase.CONTINUOUS=Continuous Developer Builds
phase.EA=Early Access
phase.STABLE=Stable Release
back=Back
screen=Screen
darkMode=Dark Mode
ui=User Interface
darkMode.AUTO=Automatic
darkMode.ALWAYS=Always
darkMode.NEVER=Never
applications=Applications
font=Font
general=General
theme=Theme
default=Default
pt=Pt
resizeStrategy=Mode
resizeStrategy.NONE=None
resizeStrategy.SCREEN=Screen
resizeStrategy.FONT=Font
screenSize=Screen Size
resizing=Resizing
behaviour=Behaviour
display=Display
scrolling=Scrolling
automaticScrollBar=Show scroll bar when hovering near edge
permanentScrollBar=Show scroll bar permanently
hideScrollBar=Hide the scroll bar, scroll using keyboard actions
limitBuffer=Limit scrollback
limitBuffer.toolTip=\
	When enabled, the size of the scrollback buffer will be limited to\n\
	the chosen amount. When not enabled, the size of the scrollback buffer\n\
	will be effectively unlimited (limited by maximum memory mapped file size).
bufferSize=to
lines=Lines 
background=Background
opacity=Transparency
appearance=Appearance
shell=Shell
defaultShell=Start-up
shellInfo=The selected Start-up shell will become active the next time a new \
	terminal tab or window is opened.
customCommand=Custom command
commandAndArguments=Custom command and arguments 
matchThemeToDarkMode=Match terminal theme to current dark mode.
lorem=@'{'bold Lorem ipsum'}' dolor sit amet, consectetur adipiscing elit, sed \
	  do eiusmod tempor incididunt @'{'italic ut labore et dolore'}' magna aliqua. \
	  Ut enim ad @'{'underline minim veniam'}', quis nostrud exercitation ullamco \
	  laboris nisi @'{'inverse ut aliquip ex ea commodo'}' consequat. Duis aute \
	  irure dolor in @'{'crossedOut reprehenderit in voluptate'}' velit esse cillum \
	  @'{'faint dolore eu fugiat nulla pariatur'}'. 
noDefaultShell=No default shell found, please provide full command and arguments
passwords=Passwords
store=Remember passwords forever, keeping them in desktop keyring.
session=Remember passwords for this session.
prompt=Always prompt for passwords.
legacyPty=Use legacy Windows terminals
legacyPty.toolTip=By default, the newer Windows ConPTY mode will used to create pseudo terminals.\n\
		When this option is selected, the legacy WinPTY mode will be used.
loginShell=Login Shell
loginShell.toolTip=Whether to use a "Login Shell" on operating systems that support it. \
	This will have a slightly different environment, as if the user was \
	logging in remotely to a new session.
console=Console Mode
console.toolTip=Whether the pty should use "Console Mode", which activates a separate \
	error stream, and makes some other operating system specific adjustments.
dropInFonts=Open drop-in fonts folder
dropInThemes=Open drop-in themes folder
dropInShells=Open drop-in shells folder
accentColor=Accent Color
checkForUpdates=Check for updates
special=Special
statusLine=Status Line
statusLine.tooltip=Whether to enable the VT320 compatible host-writable status line. \
	When enabled, the default shows a simple status line, but this mode may be changed by \
	remote applications.  
fileTransferNotifications=Notifications
fileTransfers=File Transfers
downloads=Downloads
browseDownloads=Browse
fileTransferNotifications.toolTip=Whether to show desktop notifications for file transfers. 
useCurrentSize=Use current size