updates=Updates
automaticUpdates=Automatic Updates
automaticUpdates.toolTip=Whether to automatically update this application.
phase=Update Channel
phase.toolTip=The update channel from which to retrieve updates from.
phase.CONTINUOUS=Continuous Developer Builds
phase.EA=Early Access
phase.STABLE=Stable Release
back=Back
darkMode=Dark Mode
appearance=Appearance
darkMode.AUTO=Automatic
darkMode.ALWAYS=Always
darkMode.NEVER=Never
applications=Applications
font=Font
general=General
theme=Theme
default=Default
pt=Pt
resizeStrategy=Mode
resizeStrategy.NONE=None
resizeStrategy.SCREEN=Screen
resizeStrategy.FONT=Font
screenSize=Screen Size
resizing=Resizing
behaviour=Behaviour
display=Display
scrolling=Scrolling
showScrollBar=Show scroll bar
bufferSize=Limit scrollback to
lines=Lines 