;
; This file describes all the possible external shells that are searched for using the
; console protocol.
;

[cmd]
	name = DOS Command Prompt
	os = windows
	search-path = true
	paths = C:\Windows\System32

[powershell]
 	name = Microsoft Powershell
 	os = windows
 	paths = ${env:SystemRoot}\System32\WindowsPowerShell\v1.0

[msys2]
	command = msys2_shell
	name = MSys2
	arguments = -defterm, -here, -no-start, -shell, bash
	path = C:\msys64
 	os = windows
	
[mingw64]
	command = msys2_shell
	name = Mingw64 MSys2 Profile
	arguments = -defterm, -here, -no-start, -mingw64, -shell, bash
	paths = C:\msys64
 	os = windows
 	
	
[mingw32]
	command = msys2_shell
	name = Clang64 MSys2 Profile
	arguments = -defterm, -here, -no-start, -mingw32, -shell, bash
	paths = C:\msys64
 	os = windows
 	
[clang64]
	command = msys2_shell
	name = Clang64 MSys2 Profile
	arguments = -defterm, -here, -no-start, -clang64, -shell, bash
	paths = C:\msys64
 	
[clang32]
	command = msys2_shell
	name = Clang32 MSys2 Profile
	arguments = -defterm, -here, -no-start, -clang32, -shell, bash
	paths = C:\msys64
 	os = windows
 	
[clangarm64]
	command = msys2_shell
	name = ClangArm64 MSys2 Profile
	arguments = -defterm, -here, -no-start, -clangarm64, -shell, bash
	paths = C:\msys64
 	os = windows
 	
[cygwin]
	command = bash
	name = Cygwin Bash
	version-arguments = --version
	login-shell-arguments = -l
	version-pattern = .*version ([^\s].*) .*
 	os = windows
 	cygwin = true
 	paths = C:\cygwin64\bin
 	
[pwsh]
	name = Microsoft Powershell
	version-arguments = --version
	login-shell-arguments = -Login
	version-pattern = .* (.*)
	paths = /usr/bin
	search-path = true
	os = !windows
	 	
[bash]
	name = GNU Bourne-Again Shell
	version-arguments = --version
	login-shell-arguments = -l
	search-path = true
	version-pattern = .*version ([^\s].*) .*
	paths = /usr/bin
 	
[dash]
	name = POSIX Shell 	
	login-shell-arguments = -l
	search-path = true
	paths = /usr/bin

[zsh]
	name = The Z Shell
	version-argument = --version 
	login-shell-arguments = -l
	version-pattern = .* (.*) .*
	search-path = true
	paths = /usr/bin

[csh]
	name = C-like Shell 
	login-shell-arguments = -l
	search-path = true
	paths = /usr/bin