;
; This file describes all the possible external shells that are searched for using the
; console protocol.
;

[cmd]
	name = DOS Command Prompt
	os = windows
	search-path = true
	path = C:\Windows\System32

[powershell]
 	name = Microsoft Powershell
 	os = windows
 	search-path = ${env:SystemRoot}\System32\WindowsPowerShell\v1.0\powershell.exe

[msys2]
	command = mysql2_shell
	name = MSys2
	argument = -defterm
	argument = -here 	
	argument = -no-start
	argument = -shell
	argument = bash
	path = C:\msys64
 	os = windows
	
[mingw64]
	command = mysql2_shell
	name = Mingw64 MSys2 Profile
	argument = -defterm
	argument = -here 	
	argument = -no-start
	argument = -mingw64 
	argument = -shell
	argument = bash
	path = C:\msys64
 	os = windows
 	
	
[mingw64]
	command = mysql2_shell
	name = Clang64 MSys2 Profile
	argument = -defterm
	argument = -here 	
	argument = -no-start
	argument = -mingw32
	argument = -shell
	argument = bash
	path = C:\msys64
 	os = windows
 	
[mingw64]
	command = mysql2_shell
	name = Clang64 MSys2 Profile
	argument = -defterm
	argument = -here 	
	argument = -no-start
	argument = -clang64
	argument = -shell
	argument = bash
	path = C:\msys64
 	
[mingw64]
	command = mysql2_shell
	name = Clang32 MSys2 Profile
	argument = -defterm
	argument = -here 	
	argument = -no-start
	argument = -clang32
	argument = -shell
	argument = bash
	path = C:\msys64
 	os = windows
 	
[mingw64]
	command = mysql2_shell
	name = ClangArm64 MSys2 Profile
	argument = -defterm
	argument = -here 	
	argument = -no-start
	argument = -clangarm64
	argument = -shell
	argument = bash
	path = C:\msys64
 	os = windows
 	
[cygwin]
	command = bash
	name = ClangArm64 MSys2 Profile
	version-argument = --version
	login-shell-argument = -l
	version-pattern = .*version ([^\s].*) .*
 	os = windows
 	cygwin = true
 	path = C:\\cygwin64\\bin
 	
[powershell]
	command = pwsh
	name = Microsoft Powershell
	version-argument = --version
	login-shell-argument = -Login
	version-pattern = .* (.*)
	path = /usr/bin
	search-path = true
	os = !windows
	 	
[bash]
	name = GNU Bourne-Again Shell
	version-argument = --version
	login-shell-argument = -l
	search-path = true
	version-pattern = .*version ([^\s].*) .*
	path = /usr/bin
 	
[dash]
	name = POSIX Shell 	
	login-shell-argument = -l
	search-path = true
	path = /usr/bin

[zsh]
	name = The Z Shell
	version-argument = --version 
	login-shell-argument = -l
	version-pattern = .* (.*) .*
	search-path = true
	path = /usr/bin

[csh]
	name = C-like Shell 
	login-shell-argument = -l
	search-path = true
	path = /usr/bin