downloadTitle=Download
download=An application requested that you download a file.
downloadText=Do you wish to accept {0}.
accept=Accept
reject=Reject
unknownFile=Unknown File
downloadComplete=Download Complete
downloadCompleteText=The transfer of {0} is complete.
openFolder=Open Folder