appName=Pretty
options=Options
about=About
actions=Actions

message.error.icon=\uf06a
message.information.icon=\uf05a
message.warning.icon=\uf071

progress=\uf110

appType=Terminal
title=Pretty

init=Checking for updates... 
updating=Updating {0}. Please wait...
updated=Updated {0}. Waiting for service to stop.
updateFailed=Update of {0} failed. %s
waitingStart=Waiting for service to restart...
guiRestart=Restarting Desktop Application...
updateFailure=Failed to update {0}.
showException=Show full error details
availableVersion={0} is available.
installingVersion={0} is installing.
disconnected=Disconnected from {0}. 
failedToStartShell=Failed to start shell.

copied=Selection -> Clipboard
pasted=Clipboard -> Host
openUri=Open link
copyUri=Copy link to clipboard