noForwards=No forwards active
noForwardsMatch=No forwards match
local=Forwarding local @'{'bold {0}'}' from @'{'bold {1}'}' to remote @'{'bold {2}'}'
remote=Forwarding remote @'{'bold {0}'}' from @'{'bold {1}'}' to local @'{'bold {2}'}'