alreadyMounted=Remote directory / is already mounted to {0} at {1}.
connectionMounted=Remote directory / is already mounted on this connection to {0} at {1}.
mounted=Mounted
failedToMount=Failed to mount / as {0} at {1}. {2}	