authenticationFailed=Failed to authenticate @'{'bold {0}'}'
authenticated=Authenticated as @'{'bold {0}'}'
connected=Connected to @'{'bold {0}'}'
disconnected=Disconnected from @'{'bold {0}'}'
connectedToOther=You are currently connected to {0}, so must disconnect from that first before connecting to {1}.
inUse={0} is currently in use by {1}.
ssh=SSH