bold=Bold
italic=Italic
plain=Plain
noSuchFont=No such font as {0}
name=Name
size=Font Size
style=Style
charSize=Cell
invalidDestination=Invalid destination slot {0}
supplemental=Supplemental
soft=Soft
saved=Font configuration saved
flags=Flags
start=Start Codepoint
end=End Codepoint
currentFonts=Active Fonts
availableFonts=Available Fonts
nameOrNumberRequired=Font name or slot required
added=@'{'bold {0}'}' Added
removed=@'{'bold {0}'}' Removed
nameOrNumberRequired=Font name or slot required
invalidDestination=Invalid destination slot {0}
destinationRequired=Destination slot required