needsUpdate=Updates available  @'{'bold {0}'}' -> @'{'bold {1}'}'
noUpdate=No update to @'{'bold {0}'}' available.
phase=Current phase: @'{'bold {0}'}'
noUpdateAction=No update action provided, see @'{'bold update --help'}'
updating=Updating  @'{'bold {0}'}' -> @'{'bold {1}'}' ....