Material=/themes/material.ini
Material Light=/themes/material-light.ini
Material Dark=/themes/material-dark.ini
LogonBox Blue=/themes/logonbox-blue.ini
Tango=/themes/tango.ini
Tango Light=/themes/tango-light.ini
Tango Dark=/themes/tango-dark.ini
Solarized=/themes/solarized.ini
Solarized Light=/themes/solarized-light.ini
Solarized Dark=/themes/solarized-dark.ini
Sepia=/themes/sepia.ini
Sepia Dark=/themes/sepia-dark.ini
Sepia Light=/themes/sepia-light.ini
CRT Amber=/themes/crt-amber.ini
CRT Green=/themes/crt-green.ini
CRT White=/themes/crt-white.ini
Black on Light Yellow=/themes/black-on-light-yellow.ini
Black on White=/themes/black-on-white.ini
Gray on Black=/themes/grey-on-black.ini
Green on Black=/themes/green-on-black.ini
White on Black=/themes/white-on-black.ini