openUri.label=Open link
openUri.description=Open the link in the default browser for the type of file pointed at by the URI
copyUri.label=Copy link to clipboard
copyUri.description=Copy the link to the clipboard