connecting=Connecting to @'{'bold {0}@{1}:{2,number,#}'}'
remoteDisconnected=Remote disconnected.
acceptableKey=Found acceptable key @'{'bold {0}'}'
authenticatedByAgent=Authenticated by sshagent
failedToConnectToSshAgent=Failed to connect to ssh-agent
noAgent=No agent is available
identityFileDoesntExist=The identity file provided does not exist
identityFileCouldNotAuthenticate=The identity file provided could not authenticate
passwordNotSupported=Password authentication is not supported
password=Password
passphrase=Passphrase